### ISSUE TITLE
有些域名始终被chinadns过滤掉，始终拿不到解析结果

### ISSUE THREAD

**Issue by lededev** [aa65535/ChinaDNS#3]
日志如下
Tue May 29 13:43:59 2018 response router.utorrent.com from 223.5.5.5:53 - 82.221.103.244, filter
Tue May 29 13:44:00 2018 response router.utorrent.com from 223.5.5.5:53 - filter
Tue May 29 13:44:00 2018 request router.utorrent.com from 223.5.5.5:53 127.0.0.1:5300
Tue May 29 13:44:00 2018 request router.utorrent.com from 223.5.5.5:53 127.0.0.1:5300
Tue May 29 13:44:00 2018 response router.utorrent.com from 223.5.5.5:53 - filter
Tue May 29 13:44:00 2018 response router.utorrent.com from 223.5.5.5:53 - 82.221.103.244, filter
Tue May 29 13:44:01 2018 request router.utorrent.com from 223.5.5.5:53 127.0.0.1:5300
Tue May 29 13:44:01 2018 request router.utorrent.com from 223.5.5.5:53 127.0.0.1:5300
Tue May 29 13:44:01 2018 response router.utorrent.com from 223.5.5.5:53 - filter
Tue May 29 13:44:01 2018 response router.utorrent.com from 223.5.5.5:53 - 82.221.103.244, filter
Tue May 29 13:44:03 2018 request router.utorrent.com from 223.5.5.5:53 127.0.0.1:5300
Tue May 29 13:44:03 2018 request router.utorrent.com from 223.5.5.5:53 127.0.0.1:5300
Tue May 29 13:44:03 2018 response router.utorrent.com from 223.5.5.5:53 - filter
Tue May 29 13:44:03 2018 response router.utorrent.com from 223.5.5.5:53 - 82.221.103.244, filter
Tue May 29 13:44:07 2018 request router.utorrent.com from 223.5.5.5:53 127.0.0.1:5300
Tue May 29 13:44:07 2018 request router.utorrent.com from 223.5.5.5:53 127.0.0.1:5300
Tue May 29 13:44:07 2018 response router.utorrent.com from 223.5.5.5:53 - filter
Tue May 29 13:44:07 2018 response router.utorrent.com from 223.5.5.5:53 - 82.221.103.244, filter
请问如何让router.utorrent.com的解析结果正常返回？82.221.103.224这个IP实际上是可以用的，但每次被chinadns filter掉。

**Comment by lededev** [comment]
相同情况的还有emby.media这个域名。

**Comment by aa65535** [comment]
因为结果是 `223.5.5.5` 返回的，所以自然会被过滤掉，你应该检查一下 `127.0.0.1:5300` 为什么没有返回结果。

**Comment by lededev** [comment]
127.0.0.1:5300是dns-forwarder提供的，转向的是8.8.8.8:53。我PC本机DNS设置成8.8.8.8是可以解析到上面两个域名的。
/usr/bin/dns-forwarder -b 127.0.0.1 -p 5300 -s 8.8.8.8:53
/usr/bin/chinadns -m -p 5353 -s 223.5.5.5,127.0.0.1#5300 -c /etc/china_ssr.txt

**Comment by lededev** [comment]
chinadns的DNS列表要是支持3个IP就好了，分别是" 国内,信任,国外"。我可以再添加一个OpenDNS到国外那一栏，以免信任那一栏始终不返回结果，导致完全无法解析。

**Comment by ghost** [comment]
@lededev 可以试试 [overture](https://github.com/shawn1m/overture)
除了 chinadns 的基本功能 还带了 黑名单 白名单 TCP 查询 等功能 可以不用 dns-forwarder 了 也减轻了 dnsmasq 的负担
不久之前提供了 softfloat 支持  很好的支持路由器了

**Comment by aa65535** [comment]
@lededev 这个问题出自 8.8.8.8 的 TCP 模式

```
# dig router.utorrent.com @8.8.8.8 +tcp
;; communications error to 8.8.8.8#53: end of file
```

因为 `dns-forwarder` 发送的是 TCP 请求，所以没有了返回。

可以添加 `server=/utorrent.com/223.5.5.5` 到 `/etc/dnsmasq.conf` ，
或者在 网络 -> DHCP/DNS -> DNS 转发 里面添加上 `/utorrent.com/223.5.5.5`

**Comment by lededev** [comment]
@suikatomoki suikatomoki overture又是拿go开发的，我路由器只有16MB FlashROM真心放不下那些go程序。
@aa65535 原来如此，你的解决办法我试过了可用，反正这样的域名不多就先这样凑合吧，谷歌的DNS也掉链子啊，不知有何途径向他们反馈一下。

**Comment by lededev** [comment]
@aa65535 有没考虑把GFWList也从dnsmasq那边拿过来，再维护一下ipset，dnsmasq就没必要装full版本了。
毕竟没进那个名单的域名基本上就不可能被污染，直接用国内域名服务器做解析完全没问题，只有名单上的域名才尝试用境外DNS来查询。

**Comment by aa65535** [comment]
@lededev 这个应该不是 8.8.8.8 阻断了连接，而是服务器的提供商做了禁止（大概是涉及到版权？），至少我测试的香港的服务器是不能正常返回，日本的倒是没有问题。

ChinaDNS 应该不会添加新的功能了，毕竟 dnsmasq 或者其他工具可以做到这些。
